### ISSUE TITLE
Uncaught Exception: FPDF error

### ISSUE THREAD

**Issue by konradstrek** [farjadtahir/pdf-invoicr#27]
Right after moving the files into Xampp folder, I have following errors.
Using PHP 7.3.11
```
Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\invoices\phpinvoice.php on line 715

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\invoices\phpinvoice.php on line 715

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\invoices\phpinvoice.php on line 715

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\invoices\phpinvoice.php on line 715

Fatal error: Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file in C:\xampp\htdocs\invoices\inc\fpdf\fpdf.php:271 Stack trace: #0 C:\xampp\htdocs\invoices\inc\fpdf\fpdf.php(1063): FPDF->Error('Some data has a...') #1 C:\xampp\htdocs\invoices\inc\fpdf\fpdf.php(999): FPDF->_checkoutput() #2 C:\xampp\htdocs\invoices\phpinvoice.php(332): FPDF->Output('I', 'example1.pdf') #3 C:\xampp\htdocs\invoices\examples\example1.php(32): phpinvoice->render('example1.pdf', 'I') #4 {main} thrown in C:\xampp\htdocs\invoices\inc\fpdf\fpdf.php on line 271
```

**Comment by konradstrek** [comment]
Fixed by chaning PHP version from 7.31 to 5.6
